apiVersion: v1
kind: Service
metadata:
  name: airflow-apiserver-service
  namespace: airflows
  labels:
    app: airflow-apiserver
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: airflow-apiserver