# Final deployment-airflow-worker.yaml configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: airflows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
        azure.workload.identity/client-id: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
    spec:
      serviceAccountName: airflow-worker-sa
      containers:
        - name: airflow-worker
          image: registryacr.azurecr.io/airflow-worker:0.0.17
          command: ["bash", "-c"]
          args:
            - |
              # Install all dependencies from requirements.txt
              pip install --quiet -r /opt/airflow/requirements/requirements.txt

              # Start log server and worker with stable hostname
              airflow celery serve-logs --address 0.0.0.0 --port 8793 &
              SERVE_LOGS_PID=$!
              trap "kill $SERVE_LOGS_PID" EXIT

              exec airflow celery worker --celery-hostname airflow-worker
          ports:
            - containerPort: 8793
              name: logs
          
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
              
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-db-secret
                  key: connection
            - name: AZURE_TENANT_ID
              value: "63bcd176-823a-4129-bd6b-cd6142a0b825"
            - name: AZURE_CLIENT_ID
              value: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
            - name: AZURE_AUTHORITY_HOST
              value: "https://login.microsoftonline.com/"
            - name: AZURE_VAULT_URL
              value: "https://bci-keyss.vault.azure.net/"
            - name: PYTHONPATH
              value: "/opt/airflow/plugins:/opt/airflow/plugins/bci_source:/opt/airflow"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            # --- CRITICAL ADDITION BELOW ---
            - name: AIRFLOW__CELERY__WORKER_POOL
              value: "solo"
            # --- END OF ADDITION ---
            - name: AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT
              value: "8793"
            - name: AIRFLOW__CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: airflow-broker-secret
                  key: broker_url
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-broker-secret
                  key: result_backend_url
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
                  optional: true
            - name: AIRFLOW__CORE__AIRFLOW_API_BASE_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__API__AIRFLOW_API_BASE_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__WEBSERVER__BASE_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__AIRFLOW_SDK__API__CLIENT__ENDPOINT_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080/execution/"
          volumeMounts:
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
              readOnly: true
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: airflow-requirements
              mountPath: /opt/airflow/requirements
              readOnly: true
      volumes:
        - name: airflow-config
          configMap:
            name: airflow-config
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-requirements
          configMap:
            name: airflow-requirements
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-worker-sa
  namespace: airflows
  annotations:
    azure.workload.identity/client-id: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  namespace: airflows
spec:
  selector:
    app: airflow-worker
  ports:
    - name: logs
      port: 8793
      targetPort: 8793
