# Final deployment-airflow-scheduler.yaml manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
        azure.workload.identity/client-id: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
    spec:
      serviceAccountName: airflow-scheduler-sa
      containers:
        - name: airflow-scheduler
          image: registryacr.azurecr.io/airflow-scheduler:0.0.17
          command: ["bash", "-c"]
          args:
            - |
              # Install PySpark if it is not already present
              pip install pyspark==3.4.0 --quiet
              
              # Start the DAG processor in the background
              airflow dag-processor &
              
              # Wait briefly for the DAG processor to initialize
              sleep 5
              
              # Start the scheduler
              airflow scheduler
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            # --- FINAL ADDITION BELOW ---
            - name: AIRFLOW__CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: airflow-broker-secret
                  key: broker_url
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: airflow-broker-secret
                  key: result_backend_url
            # --- END OF ADDITION ---
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-db-secret
                  key: connection
            - name: AZURE_TENANT_ID
              value: "63bcd176-823a-4129-bd6b-cd6142a0b825"
            - name: AZURE_CLIENT_ID
              value: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
            - name: AZURE_AUTHORITY_HOST
              value: "https://login.microsoftonline.com/"
            - name: AZURE_VAULT_URL
              value: "https://bci-keyss.vault.azure.net/"
            - name: PYTHONPATH
              value: "/opt/airflow/plugins:/opt/airflow/plugins/bci_source:/opt/airflow"
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
                  optional: true
            - name: AIRFLOW__CORE__AIRFLOW_API_BASE_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__API__AIRFLOW_API_BASE_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__WEBSERVER__BASE_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__AIRFLOW_SDK__API__CLIENT__ENDPOINT_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080"
            - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
              value: "http://airflow-apiserver-service.airflows.svc.cluster.local:8080/execution/"
          volumeMounts:
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
              readOnly: true
            - name: airflow-logs
              mountPath: /opt/airflow/logs
      volumes:
        - name: airflow-config
          configMap:
            name: airflow-config
        - name: airflow-logs  
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-scheduler-sa
  namespace: airflows
  annotations:
    azure.workload.identity/client-id: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
