apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  namespace: airflows
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
        azure.workload.identity/client-id: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
    spec:
      serviceAccountName: airflow-triggerer-sa
      containers:
        - name: airflow-triggerer
          image: registryacr.azurecr.io/airflow-triggerer:0.0.17
          command: ["bash", "-c"]
          args:
            - |
              # Install PySpark if it is not already present
              pip install pyspark==3.4.0 --quiet

              # Start the triggerer
              airflow triggerer
          env:
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-db-secret
                  key: connection
            - name: AZURE_TENANT_ID
              value: "63bcd176-823a-4129-bd6b-cd6142a0b825"
            - name: AZURE_CLIENT_ID
              value: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
            - name: AZURE_AUTHORITY_HOST
              value: "https://login.microsoftonline.com/"
            - name: AZURE_VAULT_URL
              value: "https://bci-keyss.vault.azure.net/"
            - name: PYTHONPATH
              value: "/opt/airflow/plugins:/opt/airflow"
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
                  optional: true
          volumeMounts:
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
              readOnly: true
      volumes:
        - name: airflow-config
          configMap:
            name: airflow-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-triggerer-sa
  namespace: airflows
  annotations:
    azure.workload.identity/client-id: "3a7bbade-a271-459a-aa8b-42ccf53a6aac"
